baseURL: https://ourlife.ml/
languageCode: en
title: My dev blog
theme: stack

params:
  favicon: coding.ico
  sidebar:
    emoji: 🤓
    avatar:
      enabled: true
      local: false
      src: img/avatar.png

  footer:
    since: 2022
    customText: "Made for programmers by a programmer"


